name: LinkGrabber

on:
  schedule:
    - cron: '*/60 * * * *'

  pull_request:
    branches: [ main ]

  workflow_dispatch:
jobs:

  runCode:

    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Grab Link

        run: |
          git config --global user.email "fbk@hll.localhost"
          git config --global user.name "fbk"
          chmod +x autorun.sh && ./autorun.sh
          git commit -m "./youtubeLink.txt is updated."
          git push
